version: "3.9"

services:

  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 0.0.0.0:8000:80
    volumes:
    - ./app:/var/www/html
    - ./configs/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx

  php-fpm:
    build:
      context: ./
      dockerfile: ./build/php.dockerfile
    depends_on:
      - db
    volumes:
    - ./app:/var/www/html

  db:
    image: mysql:latest
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: userpass
    volumes:
      - ./db-dumps/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
      - db
    ports:
    - 127.0.0.1:8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
