version: "3.9"

services:

  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - ${IP}:8000:80
    volumes:
      - ./app:/var/www/html
      - ./configs/nginx:/etc/nginx/conf.d

  php-fpm:
    build:
      context: ./
      dockerfile: ./build/php.dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:latest
    ports:
      - ${IP}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./db-dumps/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - ${IP}:8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD:
